apiVersion: v2
name: draft-store-service
home: https://github.com/hmcts/draft-store
version: 2.1.7
description: Draft store
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: 4.1.5
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: postgresql
    version: 0.0.5
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: postgresql.enabled