apiVersion: v2
name: draft-store-service
home: https://github.com/hmcts/draft-store
version: 2.0.6
description: Draft store
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: 3.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
