java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DRAFT_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
    DRAFT_STORE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    DRAFT_STORE_DB_USER_NAME: "{{ .Values.postgresql.auth.username}}"
    DRAFT_STORE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    RUN_DB_MIGRATION_ON_STARTUP: true
    DRAFT_STORE_DB_CONN_OPTIONS: ""
  postgresql:
    enabled: true
  keyVaults:
    "draft-store":
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string